// tracker-react/src/components/StepsCard.jsx
import React, { useState, useEffect } from "react";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const StepsCard = () => {
  const stepsGoal = 10000;

  // Load saved steps + streak
  const [steps, setSteps] = useState(() => {
    return parseInt(localStorage.getItem("steps") || "0", 10);
  });
  const [streak, setStreak] = useState(() => {
    return parseInt(localStorage.getItem("streak") || "0", 10);
  });
  const [tip, setTip] = useState("");

  const tips = [
    "🚶 Take short walking breaks every hour.",
    "🛗 Use stairs instead of elevators.",
    "🎶 Walk while listening to your favorite podcast.",
    "🏞️ Take a walk outside for fresh air.",
    "👟 Track your steps to stay motivated.",
  ];

  const stepsPct = Math.min(100, Math.round((steps / stepsGoal) * 100));

  // Persist to localStorage
  useEffect(() => {
    localStorage.setItem("steps", steps);
    localStorage.setItem("streak", streak);
  }, [steps, streak]);

  // Update tip randomly
  const getRandomTip = () => {
    const newTip = tips[Math.floor(Math.random() * tips.length)];
    setTip(newTip);
  };

  // Handle +500 steps click
  const handleAddSteps = () => {
    const newSteps = steps + 500;
    setSteps(newSteps);
    getRandomTip();

    if (newSteps >= stepsGoal) {
      toast.success("🎉 Amazing! You reached today’s step goal!");
    } else if (newSteps >= stepsGoal * 0.7) {
      toast.info("💪 Almost there! Keep moving!");
    }
  };

  // Handle daily reset and streak increment
  const handleDailyReset = () => {
    setSteps(0);
    setStreak((prev) => prev + 1);
    getRandomTip();
    toast.success(`🔥 You’ve walked ${streak + 1} days in a row. Keep it up!`);
  };

  return (
    <div className="bg-white rounded-2xl p-6 shadow-sm">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <svg
            className="w-5 h-5 text-orange-400"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M5 12h14M12 5v14" />
          </svg>
          <h3 className="font-medium">Steps</h3>
        </div>
        <span className="text-sm text-orange-500 font-medium">
            🔥 {streak}-day streak
          </span>
      </div>

      <div className="text-3xl font-semibold">{steps.toLocaleString()}</div>

      <div className="w-full bg-slate-100 rounded-full h-3 mt-4 overflow-hidden">
        <div
          style={{ width: `${stepsPct}%` }}
          className="h-3 rounded-full bg-gradient-to-r from-sky-400 to-emerald-400"
        ></div>
      </div>

      <div className="text-sm text-slate-400 mt-3">
        Goal: {stepsGoal.toLocaleString()} ({stepsPct}%)
      </div>

      <div className="mt-4 flex gap-2">
        <button
          onClick={handleAddSteps}
          className="px-3 py-1 bg-slate-100 rounded hover:bg-slate-200"
        >
          +500 steps
        </button>
        <button
          onClick={handleDailyReset}
          className="px-3 py-1 bg-slate-100 rounded hover:bg-slate-200"
        >
          Reset (Daily)
        </button>
      </div>

      {/* Random Motivational Tip */}
      <div className="mt-4 p-3 text-sm bg-orange-50 rounded-lg text-orange-700">
        💡 Tip: {tip}
      </div>

      <ToastContainer position="top-right" autoClose={3000} />
    </div>
  );
};

export default StepsCard;

// tracker-angular/src/app/components/steps-card/steps-card.component.ts
import { Component, OnInit } from '@angular/core';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-steps-card',
  standalone: true, // ✅ make standalone
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatProgressBarModule,
    MatSnackBarModule
  ],
  templateUrl: './steps-card.component.html',
  styleUrls: ['./steps-card.component.scss']
})
export class StepsCardComponent implements OnInit {
  stepsGoal = 10000;
  steps: number = 0;
  streak: number = 0;
  tip: string = '';

  tips: string[] = [
    "🚶 Take short walking breaks every hour.",
    "🛗 Use stairs instead of elevators.",
    "🎶 Walk while listening to your favorite podcast.",
    "🏞️ Take a walk outside for fresh air.",
    "👟 Track your steps to stay motivated."
  ];

  constructor(private snackBar: MatSnackBar) {}

  ngOnInit(): void {
    this.steps = parseInt(localStorage.getItem("steps") || "0", 10);
    this.streak = parseInt(localStorage.getItem("streak") || "0", 10);
  }

  get stepsPct(): number {
    return Math.min(100, Math.round((this.steps / this.stepsGoal) * 100));
  }

  private saveToStorage(): void {
    localStorage.setItem("steps", this.steps.toString());
    localStorage.setItem("streak", this.streak.toString());
  }

  private getRandomTip(): void {
    this.tip = this.tips[Math.floor(Math.random() * this.tips.length)];
  }

  handleAddSteps(): void {
    this.steps += 500;
    this.saveToStorage();
    this.getRandomTip();

    if (this.steps >= this.stepsGoal) {
      this.snackBar.open("🎉 Amazing! You reached today’s step goal!", "Close", { duration: 3000 });
    } else if (this.steps >= this.stepsGoal * 0.7) {
      this.snackBar.open("💪 Almost there! Keep moving!", "Close", { duration: 3000 });
    }
  }

  handleDailyReset(): void {
    this.steps = 0;
    this.streak += 1;
    this.saveToStorage();
    this.getRandomTip();
    this.snackBar.open(`🔥 You’ve walked ${this.streak} days in a row. Keep it up!`, "Close", { duration: 3000 });
  }
}

<mat-card class="steps-card">
  <mat-card-header>
    <mat-card-title>
      <div class="header">
        <span>🚶 Steps</span>
        <span class="streak">🔥 {{ streak }}-day streak</span>
      </div>
    </mat-card-title>
  </mat-card-header>

  <mat-card-content>
    <div class="steps-count">{{ steps | number }}</div>

    <mat-progress-bar
      mode="determinate"
      [value]="stepsPct"
      class="progress"
    ></mat-progress-bar>

    <div class="goal">Goal: {{ stepsGoal | number }} ({{ stepsPct }}%)</div>

    <div class="actions">
      <button mat-stroked-button color="primary" (click)="handleAddSteps()">
        +500 steps
      </button>
      <button mat-stroked-button color="warn" (click)="handleDailyReset()">
        Reset (Daily)
      </button>
    </div>

    <div class="tip">
      💡 Tip: {{ tip || 'Click +500 to see a random tip!' }}
    </div>
  </mat-card-content>
</mat-card>
