// tracker-angular/src/app/components/goals-card/goals-card.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatProgressBarModule } from '@angular/material/progress-bar';

@Component({
  selector: 'app-goals-card',
  standalone: true, // <- mark as standalone
  imports: [
    CommonModule,       // for *ngIf, *ngFor
    MatCardModule,      // for <mat-card>
    MatProgressBarModule // for <mat-progress-bar>
  ],
  templateUrl: './goals-card.component.html',
  styleUrls: ['./goals-card.component.scss']
})
export class GoalsCardComponent implements OnInit {
  data: any = null;
  badges: string[] = [];

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.data = {
      cigGoal: parseInt(localStorage.getItem('cigGoal') || '5', 10),
      cigs: parseInt(localStorage.getItem('cigs') || '0', 10),
      exerciseHistory: JSON.parse(localStorage.getItem('exerciseHistory') || '[]'),
      exerciseStreak: parseInt(localStorage.getItem('exerciseStreak') || '0', 10),
      meals: JSON.parse(localStorage.getItem('meals') || '{}'),
      moodLog: JSON.parse(localStorage.getItem('moodLog') || '{}'),
      moodStreak: parseInt(localStorage.getItem('moodStreak') || '0', 10),
    };
    this.calculateBadges();
  }

  get cigProgress(): number {
    return Math.max(0, ((this.data.cigGoal - this.data.cigs) / this.data.cigGoal) * 100);
  }

  get exerciseProgress(): number {
    return Math.min(100, (this.data.exerciseStreak / 30) * 100);
  }

  get moodProgress(): number {
    return Math.min(100, (this.data.moodStreak / 7) * 100);
  }

  calculateBadges(): void {
    this.badges = [];
    if (this.data.cigs === 0) this.badges.push('🥉 Smoke-Free Today');
    if (this.data.exerciseStreak >= 5) this.badges.push('🔥 5-Day Exercise Streak');
    if (Object.values(this.data.meals).some((m: any) => m)) this.badges.push('🍎 Healthy Meals Logged');
    if (this.data.moodStreak >= 2) this.badges.push('🌞 Positive Mood Streak');
  }
}

// tracker-react/src/components/GoalsCard.jsx
import React, { useState, useEffect } from "react";

const GoalsCard = () => {
  const [data, setData] = useState(null);

  useEffect(() => {
    const savedData = {
      cigGoal: parseInt(localStorage.getItem("cigGoal")) || 5,
      cigs: parseInt(localStorage.getItem("cigs")) || 0,
      exerciseHistory: JSON.parse(localStorage.getItem("exerciseHistory")) || [],
      exerciseStreak: parseInt(localStorage.getItem("exerciseStreak")) || 0,
      meals: JSON.parse(localStorage.getItem("meals")) || {},
      moodLog: JSON.parse(localStorage.getItem("moodLog")) || {},
      moodStreak: parseInt(localStorage.getItem("moodStreak")) || 0,
    };
    setData(savedData);
  }, []);

  if (!data) return <p>Loading...</p>;

  // Progress calculation
  const cigProgress = Math.max(0, ((data.cigGoal - data.cigs) / data.cigGoal) * 100);
  const exerciseProgress = Math.min(100, (data.exerciseStreak / 30) * 100); // 30-day challenge
  const moodProgress = Math.min(100, (data.moodStreak / 7) * 100); // 1-week streak goal

  // Badges
  const badges = [];

  if (data.cigs === 0) badges.push("🥉 Smoke-Free Today");
  if (data.exerciseStreak >= 5) badges.push("🔥 5-Day Exercise Streak");
  if (Object.values(data.meals).some((m) => m)) badges.push("🍎 Healthy Meals Logged");
  if (data.moodStreak >= 2) badges.push("🌞 Positive Mood Streak");

  return (
    <div className="bg-white rounded-2xl p-6 shadow-sm">
      <h1 className="text-2xl font-bold mb-4">Your Goals & Progress</h1>

      {/* Cigarettes */}
      <div className="mb-4">
        <h2 className="font-semibold">Cigarette Goal</h2>
        <p>{data.cigs}/{data.cigGoal} today</p>
        <div className="w-full bg-gray-200 rounded-full h-3">
          <div className="bg-green-500 h-3 rounded-full" style={{ width: `${cigProgress}%` }} />
        </div>
      </div>

      {/* Exercise */}
      <div className="mb-4">
        <h2 className="font-semibold">Exercise Streak</h2>
        <p>{data.exerciseStreak} days</p>
        <div className="w-full bg-gray-200 rounded-full h-3">
          <div className="bg-blue-500 h-3 rounded-full" style={{ width: `${exerciseProgress}%` }} />
        </div>
      </div>

      {/* Mood */}
      <div className="mb-4">
        <h2 className="font-semibold">Mood Streak</h2>
        <p>{data.moodStreak} days</p>
        <div className="w-full bg-gray-200 rounded-full h-3">
          <div className="bg-yellow-500 h-3 rounded-full" style={{ width: `${moodProgress}%` }} />
        </div>
      </div>

      {/* Badges */}
      <div className="mt-6">
        <h2 className="font-semibold">Your Badges</h2>
        <div className="flex gap-2 flex-wrap mt-2">
          {badges.length > 0 ? (
            badges.map((badge, i) => (
              <span key={i} className="px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-sm">
                {badge}
              </span>
            ))
          ) : (
            <p>No badges yet — keep going!</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default GoalsCard;
