// tracker-angular/src/app/components/mood-calendar/mood-calendar.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import {
  eachDayOfInterval,
  startOfMonth,
  endOfMonth,
  format,
  isToday
} from 'date-fns';

interface Mood {
  key: string;
  label: string;
  emoji: string;
  color: string;
}

@Component({
  selector: 'app-mood-calendar',
  standalone: true,
  templateUrl: './mood-calendar.component.html',
  styleUrls: ['./mood-calendar.component.scss'],
  imports: [CommonModule, MatCardModule]
})
export class MoodCalendarComponent implements OnInit {
  moods: Mood[] = [
    { key: 'sad', label: 'Sad', emoji: '😔', color: 'blue' },
    { key: 'meh', label: 'Meh', emoji: '😐', color: 'gray' },
    { key: 'happy', label: 'Happy', emoji: '😊', color: 'yellow' },
    { key: 'excited', label: 'Excited', emoji: '🤩', color: 'orange' },
    { key: 'party', label: 'Party', emoji: '🥳', color: 'pink' },
  ];

  moodLog: Record<string, string> = {};
  days: Date[] = [];

  ngOnInit(): void {
    this.moodLog = JSON.parse(localStorage.getItem('moodLog') || '{}');

    this.days = eachDayOfInterval({
      start: startOfMonth(new Date()),
      end: endOfMonth(new Date()),
    });
  }

  getMoodForDay(day: Date): Mood | undefined {
    const dayKey = format(day, 'yyyy-MM-dd');
    return this.moods.find(m => m.key === this.moodLog[dayKey]);
  }

  getDayLabel(day: Date, mood?: Mood): string {
    return mood ? mood.emoji : format(day, 'd');
  }

  isToday(day: Date): boolean {
    return isToday(day);
  }

  getDayKey(day: Date): string {
    return format(day, 'yyyy-MM-dd');
  }
}

<mat-card class="mood-calendar">
  <h4 class="title">Mood Calendar</h4>

  <div class="calendar-grid">
    <div
      *ngFor="let day of days"
      class="day-cell"
      [ngClass]="[
        getMoodForDay(day)?.color || 'default',
        isToday(day) ? 'today' : ''
      ]"
      [attr.title]="getMoodForDay(day)?.label || 'No mood logged'"
    >
      {{ getDayLabel(day, getMoodForDay(day)) }}
    </div>
  </div>
</mat-card>

// tracker-react/src/components/MoodCalendar.jsx
import React, { useState } from 'react';
import { eachDayOfInterval, startOfMonth, endOfMonth, format, isToday } from 'date-fns';

const MoodCalendar = () => {
  const moods = [
    { key: 'sad', label: 'Sad', emoji: '😔', color: 'bg-blue-200' },
    { key: 'meh', label: 'Meh', emoji: '😐', color: 'bg-gray-200' },
    { key: 'happy', label: 'Happy', emoji: '😊', color: 'bg-yellow-200' },
    { key: 'excited', label: 'Excited', emoji: '🤩', color: 'bg-orange-200' },
    { key: 'party', label: 'Party', emoji: '🥳', color: 'bg-pink-200' },
  ];

  const moodLog = JSON.parse(localStorage.getItem('moodLog')) || {};

  const days = eachDayOfInterval({
    start: startOfMonth(new Date()),
    end: endOfMonth(new Date()),
  });

  return (
    <div className="max-w-md mx-auto p-6 bg-white rounded-2xl shadow-md mt-6">
      <h4 className="font-medium mb-2">Mood Calendar</h4>
      <div className="grid grid-cols-7 gap-2">
        {days.map(day => {
          const dayKey = format(day, 'yyyy-MM-dd');
          const moodEntry = moods.find(m => m.key === moodLog[dayKey]);
          return (
            <div
              key={dayKey}
              className={`flex items-center justify-center h-12 w-12 rounded-md cursor-pointer ${
                moodEntry ? moodEntry.color : 'bg-gray-100'
              } ${isToday(day) ? 'ring-2 ring-sky-400' : ''}`}
              title={moodEntry ? moodEntry.label : 'No mood logged'}
            >
              {moodEntry ? moodEntry.emoji : format(day, 'd')}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default MoodCalendar;
