// tracker-angular/src/app/components/moods-card/moods-card.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSnackBar } from '@angular/material/snack-bar';
import { format } from 'date-fns';

interface Mood {
  key: string;
  label: string;
  emoji: string;
  color: string;
  message: string;
}

@Component({
  selector: 'app-moods-card',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule
  ],
  templateUrl: './moods-card.component.html',
  styleUrls: ['./moods-card.component.scss']
})
export class MoodsCardComponent implements OnInit {
  moods: Mood[] = [
    { key: 'sad', label: 'Sad', emoji: '😔', color: 'blue', message: 'It’s okay to feel sad 💙' },
    { key: 'meh', label: 'Meh', emoji: '😐', color: 'gray', message: 'Stay steady 🌱' },
    { key: 'happy', label: 'Happy', emoji: '😊', color: 'yellow', message: 'Keep smiling 😄' },
    { key: 'excited', label: 'Excited', emoji: '🤩', color: 'orange', message: 'Your energy is contagious ✨' },
    { key: 'party', label: 'Party', emoji: '🥳', color: 'pink', message: 'Celebrate and enjoy 🎉' },
  ];

  todayKey = format(new Date(), 'yyyy-MM-dd');
  mood: string = 'happy';
  journal: string = '';
  streak: number = 0;
  moodLog: Record<string, string> = {};

  constructor(private snackBar: MatSnackBar) {}

  ngOnInit(): void {
    this.mood = localStorage.getItem('todayMood') || 'happy';
    this.journal = localStorage.getItem('todayJournal') || '';
    this.streak = parseInt(localStorage.getItem('moodStreak') || '0', 10);
    this.moodLog = JSON.parse(localStorage.getItem('moodLog') || '{}');
  }

  get currentMood(): Mood | undefined {
    return this.moods.find(m => m.key === this.mood);
  }

  handleMoodClick(key: string) {
    this.mood = key;
    localStorage.setItem('todayMood', key);

    if (['happy', 'excited', 'party'].includes(key)) {
      this.streak++;
      localStorage.setItem('moodStreak', this.streak.toString());
    } else {
      this.streak = 0;
      localStorage.setItem('moodStreak', '0');
    }

    this.moodLog[this.todayKey] = key;
    localStorage.setItem('moodLog', JSON.stringify(this.moodLog));

    const moodObj = this.moods.find(m => m.key === key);
    if (moodObj) {
      this.snackBar.open(moodObj.message, 'OK', { duration: 3000 });
    }
  }

  handleJournalChange(value: string) {
    this.journal = value;
    localStorage.setItem('todayJournal', value);
  }
}

<mat-card class="moods-card">
  <div class="header">
    <h3>Mood Today</h3>
  </div>

  <!-- Current Mood -->
  <div class="current-mood" *ngIf="currentMood">
    <div class="emoji">{{ currentMood.emoji }}</div>
    <div class="label">{{ currentMood.label }}</div>
  </div>

  <!-- Mood buttons -->
  <div class="mood-buttons">
    <button
      mat-fab
      *ngFor="let m of moods"
      (click)="handleMoodClick(m.key)"
      [ngClass]="{ active: m.key === mood }">
      {{ m.emoji }}
    </button>
  </div>

  <!-- Journal -->
  <mat-form-field appearance="outline" class="journal">
    <mat-label>Journal</mat-label>
    <textarea matInput [(ngModel)]="journal" (ngModelChange)="handleJournalChange($event)"></textarea>
  </mat-form-field>

  <!-- Streak -->
  <div class="streak">
    <span class="highlight">🔥 {{ streak }} days</span>
  </div>
</mat-card>

// tracker-react/src/components/MoodsCard.jsx
import React, { useState } from 'react';
import { toast, ToastContainer } from 'react-toastify';
import { format } from 'date-fns';
import 'react-toastify/dist/ReactToastify.css';

const MoodsCard = () => {
  const moods = [
    { key: 'sad', label: 'Sad', emoji: '😔', color: 'bg-blue-200', message: 'It’s okay to feel sad 💙' },
    { key: 'meh', label: 'Meh', emoji: '😐', color: 'bg-gray-200', message: 'Stay steady 🌱' },
    { key: 'happy', label: 'Happy', emoji: '😊', color: 'bg-yellow-200', message: 'Keep smiling 😄' },
    { key: 'excited', label: 'Excited', emoji: '🤩', color: 'bg-orange-200', message: 'Your energy is contagious ✨' },
    { key: 'party', label: 'Party', emoji: '🥳', color: 'bg-pink-200', message: 'Celebrate and enjoy 🎉' },
  ];

  const todayKey = format(new Date(), 'yyyy-MM-dd');
  const [mood, setMood] = useState(() => localStorage.getItem('todayMood') || 'happy');
  const [journal, setJournal] = useState(() => localStorage.getItem('todayJournal') || '');
  const [streak, setStreak] = useState(() => parseInt(localStorage.getItem('moodStreak')) || 0);
  const [moodLog, setMoodLog] = useState(() => JSON.parse(localStorage.getItem('moodLog')) || {});

  const handleMoodClick = (key) => {
    setMood(key);
    localStorage.setItem('todayMood', key);

    if (['happy', 'excited', 'party'].includes(key)) {
      const newStreak = streak + 1;
      setStreak(newStreak);
      localStorage.setItem('moodStreak', newStreak);
    } else {
      setStreak(0);
      localStorage.setItem('moodStreak', 0);
    }

    const newLog = { ...moodLog, [todayKey]: key };
    setMoodLog(newLog);
    localStorage.setItem('moodLog', JSON.stringify(newLog));

    const moodObj = moods.find(m => m.key === key);
    toast.info(moodObj.message, { position: 'top-center', autoClose: 3000 });
  };

  const handleJournalChange = (e) => {
    setJournal(e.target.value);
    localStorage.setItem('todayJournal', e.target.value);
  };

  return (
    <div className="max-w-md mx-auto p-6 bg-white rounded-2xl shadow-md">
      <div className="flex flex-col items-center mb-4">
        <h3 className="font-medium mb-2">Mood Today</h3>
        <div className="text-6xl mb-2">{moods.find(m => m.key === mood)?.emoji}</div>
        <div className="text-lg font-medium mb-4">{moods.find(m => m.key === mood)?.label}</div>

        <div className="flex gap-3 mb-4">
          {moods.map(m => (
            <button
              key={m.key}
              onClick={() => handleMoodClick(m.key)}
              className={`p-2 rounded-full text-lg transition-all ${m.key === mood ? 'ring-2 ring-sky-300 scale-110' : 'opacity-70 hover:scale-105'}`}
            >
              {m.emoji}
            </button>
          ))}
        </div>

        <textarea
          value={journal}
          onChange={handleJournalChange}
          placeholder="Write a quick note..."
          className="w-full p-2 border border-gray-300 rounded-md mb-3 resize-none"
          rows={2}
        />

        <div className="text-sm text-gray-500">
          Current Happy Streak: <span className="text-sm text-orange-500 font-medium">
            🔥 {streak}-days
          </span>
        </div>
        
      </div>
      <ToastContainer />
    </div>
  );
};

export default MoodsCard
